[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "grandine-py"
version = "0.1.1"
description = "Python bindings for Grandine crates"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
